language: ruby

rvm:
  - 2.2.0

before_install:

before_script:
  - phantomjs --version
  - bundle exec jekyll serve &
  - sleep 3

script:
  - curl localhost:4000

notifications:
  slack: sblei:hjdLbikaX1Pvwz5hsoeSvw8f
