# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: bleifrei.xyz
name: bleifrei.xyz
tagline: Brew hack.
email: s.blei@mail.ru
description: > # this means to ignore newlines until "baseurl:"
  Informationen über Bier von Sebastian Blei & Söhnen.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bleifrei.xyz" # the base hostname & protocol for your site
twitter_username: iamblei
github_username:  iamsebastian

# Build settings
markdown: kramdown

github:
  url: "https://iamsebastian.github.io/bleifrei.xyz"

gems:
  - jekyll-sitemap

exclude:
  - vendor
